library(vcfR)
vcf1<-read.vcfR("D:\\EDUCA\\ClAS\\FAMExomes.genotyped.vcf",verbose=FALSE)
vcf2<-read.vcfR("D:\\EDUCA\\ClAS\\FAMExomes.ann.vcf",verbose=FALSE)
chrom1 <- create.chromR(name='genotyped', vcf=vcf1)
chrom2 <- create.chromR(name='annotated', vcf=vcf2)
chrom1 <- masker(chrom1, min_QUAL = 1, max_QUAL=15000, min_DP = 30, max_DP = 800, min_MQ = 59.9,  max_MQ = 60.1)
plot(chrom1)
#chrom2 <- masker(chrom2, min_QUAL = 1, max_QUAL=15000, min_DP = 30, max_DP = 800, min_MQ = 59.9,  max_MQ = 60.1)
#plot(chrom2)
chromoqc(chrom1, dp.alpha=20)
#chromoqc(chrom2, dp,alpha=20)